// This is the top level module
module TwoBitSelector(
	input a0,
	input a1,
	input b0,
	input b1,
	input s0,
	input s1,
	output f0,
	output f1
);

wire	SYNTHESIZED_WIRE_0;
wire	SYNTHESIZED_WIRE_1;
wire	SYNTHESIZED_WIRE_2;
wire	SYNTHESIZED_WIRE_3;
wire	SYNTHESIZED_WIRE_4;
wire	SYNTHESIZED_WIRE_5;
wire	SYNTHESIZED_WIRE_6;
wire	SYNTHESIZED_WIRE_7;
wire	SYNTHESIZED_WIRE_8;
wire	SYNTHESIZED_WIRE_9;
wire	SYNTHESIZED_WIRE_24;
wire	SYNTHESIZED_WIRE_11;
wire	SYNTHESIZED_WIRE_25;
wire	SYNTHESIZED_WIRE_13;
wire	SYNTHESIZED_WIRE_16;
wire	SYNTHESIZED_WIRE_17;
wire	SYNTHESIZED_WIRE_19;
wire	SYNTHESIZED_WIRE_21;



assign	SYNTHESIZED_WIRE_24 =  ~s0;

assign	f1 = SYNTHESIZED_WIRE_0 | SYNTHESIZED_WIRE_1 | SYNTHESIZED_WIRE_2 | SYNTHESIZED_WIRE_3;

assign	f0 = SYNTHESIZED_WIRE_4 | SYNTHESIZED_WIRE_5 | SYNTHESIZED_WIRE_6 | SYNTHESIZED_WIRE_7;

assign	SYNTHESIZED_WIRE_25 =  ~s1;

assign	SYNTHESIZED_WIRE_4 = SYNTHESIZED_WIRE_8 & s1 & s0;

assign	SYNTHESIZED_WIRE_7 = SYNTHESIZED_WIRE_9 & s1 & SYNTHESIZED_WIRE_24;

assign	SYNTHESIZED_WIRE_5 = SYNTHESIZED_WIRE_11 & SYNTHESIZED_WIRE_25 & s0;

assign	SYNTHESIZED_WIRE_13 = b0 & a0;

assign	SYNTHESIZED_WIRE_21 = b1 & a1;

assign	SYNTHESIZED_WIRE_6 = SYNTHESIZED_WIRE_13 & SYNTHESIZED_WIRE_25 & SYNTHESIZED_WIRE_24;

assign	SYNTHESIZED_WIRE_0 = SYNTHESIZED_WIRE_16 & s1 & s0;

assign	SYNTHESIZED_WIRE_3 = SYNTHESIZED_WIRE_17 & s1 & SYNTHESIZED_WIRE_24;

assign	SYNTHESIZED_WIRE_1 = SYNTHESIZED_WIRE_19 & SYNTHESIZED_WIRE_25 & s0;

assign	SYNTHESIZED_WIRE_2 = SYNTHESIZED_WIRE_21 & SYNTHESIZED_WIRE_24 & SYNTHESIZED_WIRE_25;

assign	SYNTHESIZED_WIRE_17 = b1 ~^ a1;

assign	SYNTHESIZED_WIRE_9 = b0 ~^ a0;

assign	SYNTHESIZED_WIRE_19 = a1 | b1;

assign	SYNTHESIZED_WIRE_11 = a0 | b0;

assign	SYNTHESIZED_WIRE_8 =  ~a0;

assign	SYNTHESIZED_WIRE_16 =  ~a1;


endmodule
